### ISSUE TITLE
Fix it pls

### ISSUE THREAD

**Issue by ripslayer** [RyanSzczepanski/Old-Fashion-Description#8]
As per the title its not working. Thanks for this extension tho.

Ok after little testing it works and it doesn't works at the same time. What I mean is its doubling up , like the description does get extended like the old one but also new one appears too but when I try to close the new layout it totally collapses the description. 

Did another amount of testing, sometimes it doesn't work at all. So yeah 

IDK if this info will help you to fix this. I really like this extension as the new youtube update is total BS so I see some hope.

**Comment by RyanSzczepanski** [comment]
Hmm, this is interesting my version works fine, it might be the fact that YouTube pushes out updates in groups to some people and you may have a more up to date version then me.  If you could get an example of the the extension not working and screenshot the console so I can see if any errors from my extension are showing up. (If you need guidance to open the console  https://www.youtube.com/watch?v=nFFKnWw-_Ys)  If I don't get anything useful from the screenshot we can contact threw discord and I may be able to modify the extension for the version of YouTube you have.

**Comment by ripslayer** [comment]
Eh sorry for a late reply but sadly I won't be able to assist you at least for a while as I'm not available but overall I did some testing later, and that is 80% times it working if I just let the browser load the script maybe 10-15 secs I guess and then it works but if you rush to open the description it bugs out. And sometimes as I said double description. 

Also if you want you can close this issue as I will be out for a while so yeah but overall thanks for making this extension at least it does work rather than having nothing at all. So yeah thanks.

**Comment by RyanSzczepanski** [comment]
I just released an update that should alleviate the issues you are having, it will not directly fix the issue but when the plugin fully loads it will remove the new YouTube description and expand the old style description.  This should solve the double description issue and make the extension more reliable.  You can update the addon by downloading the main branch like you did to install and then replacing the old files with the new ones then going to the extensions page and refreshing the addon with the refresh button.  If you still have any issues show up feel free to open another issues thread.  I will be looking more into this to see if I can find a more permanent solution.

**Comment by RyanSzczepanski** [comment]
Version 1.0.0 should have fixed the root issue, I wish you luck using the extension!
